from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from contributors_txt.const import DEFAULT_TEAM_ROLE, NO_SHOW_MAIL, NO_SHOW_NAME
from contributors_txt.git import persons_from_shortlog

if TYPE_CHECKING:
    from contributors_txt.model import Alias, Person

LOGGER = logging.getLogger(__name__)


def create_content(
    aliases: list[Alias],
    shortlog_output: str,
    configuration_file: str,
    no_bots: bool = False,
) -> str:
    result: str = f"""\
# This file is autogenerated by 'contributors-txt',
# using the configuration in '{configuration_file}'
# please do not modify manually

"""
    persons = persons_from_shortlog(aliases, shortlog_output, no_bots=no_bots)
    result += add_teams(persons)
    result += add_contributors(persons)
    return result


def add_contributors(persons: dict[str, Person]) -> str:
    result = get_team_header(DEFAULT_TEAM_ROLE)
    for person in sorted(persons.values(), reverse=True):
        if person.team != DEFAULT_TEAM_ROLE or person.mail is None:
            continue
        if not person_should_be_shown(person):
            continue
        result += line_for_person(person)
    return result


def line_for_person(person: Person) -> str:
    assert person.mail, f"{person} do not have mail"
    return f"- {person}\n"


def person_should_be_shown(person: Person) -> bool:
    return person.mail not in NO_SHOW_MAIL and person.name not in NO_SHOW_NAME


def add_teams(persons: dict[str, Person]) -> str:
    result = ""
    teams = get_teams(persons)
    if teams:
        for team_name, team_members in teams.items():
            result += get_team_header(team_name)
            for team_member in team_members:
                if not team_member.mail:
                    LOGGER.warning("%s do not have a proper email", team_member)
                    continue
                result += line_for_person(team_member)
            result += "\n\n"
    return result


def get_team_header(team_name: str) -> str:
    return f"""\
{team_name}
{len(team_name) * '-'}
"""


def get_teams(
    persons: dict[str, Person], exclude_standard: bool = True
) -> dict[str, list[Person]]:
    teams: dict[str, list[Person]] = {}
    for person in sorted(persons.values(), reverse=True):
        if person.team != DEFAULT_TEAM_ROLE or not exclude_standard:
            members = teams.get(person.team, [])
            members.append(person)
            teams[person.team] = members
    return teams
